// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB08ESRx-PBxIIfnWGQV1G1LTAJWm01rKI',
    appId: '1:156222909726:web:6f0fc84a10f1adb3996d0f',
    messagingSenderId: '156222909726',
    projectId: 'classact13-93c1d',
    authDomain: 'classact13-93c1d.firebaseapp.com',
    storageBucket: 'classact13-93c1d.firebasestorage.app',
    measurementId: 'G-W3BM14EL9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD0ONlXFv-vFOsdGbIq3Tg979fjOEURNw',
    appId: '1:156222909726:android:a99b50b8ee83d2a1996d0f',
    messagingSenderId: '156222909726',
    projectId: 'classact13-93c1d',
    storageBucket: 'classact13-93c1d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB08ESRx-PBxIIfnWGQV1G1LTAJWm01rKI',
    appId: '1:156222909726:web:d1cdcd78a6dd9fcc996d0f',
    messagingSenderId: '156222909726',
    projectId: 'classact13-93c1d',
    authDomain: 'classact13-93c1d.firebaseapp.com',
    storageBucket: 'classact13-93c1d.firebasestorage.app',
    measurementId: 'G-M2XDMN9SNV',
  );
}
